name: Test Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Poller
        uses: ./
        with:
          file: ./logs/poller.txt
